Go
ALTER TABLE dbo.PHIEUYC
ADD TRANGTHAI NVARCHAR(50)

GO
ALTER TABLE dbo.CHITIETPHIEUYC
ADD THANHTIEN INT

GO
ALTER TABLE dbo.CHITIETPHIEUYC
ADD GIA INT

-- Đưa ra danh sách nhóm món ăn
GO
CREATE PROC NM_SelectAll
AS
BEGIN
	SELECT * FROM dbo.NHOMMONAN
END
-- Xóa nhóm món ăn
GO
ALTER PROC [dbo].[XoaNM](@MANHOMMON VARCHAR(10))
AS
BEGIN
DELETE dbo.MONAN
WHERE MANHOMMON=@MANHOMMON
DELETE dbo.NHOMMONAN
WHERE MANHOMMON=@MANHOMMON
END;
-- Thêm nhóm món
GO
ALTER PROC [dbo].[ThemNM](@MANHOMMON VARCHAR(10), @TENNHOMMON NVARCHAR(50))
AS
BEGIN
	INSERT INTO dbo.NHOMMONAN
	        ( MANHOMMON, TENNHOMMON )
	VALUES  ( @MANHOMMON,@TENNHOMMON )
END
-- Sửa nhóm món
GO
ALTER PROC [dbo].[SuaNM](@MANHOMMON VARCHAR(10), @TENNHOMMON NVARCHAR(50))
AS
BEGIN
	UPDATE dbo.NHOMMONAN
	SET TENNHOMMON=@TENNHOMMON
	WHERE MANHOMMON=@MANHOMMON
END
-- Xóa món ăn
GO
ALTER PROC [dbo].[XoaMA](@MAMON VARCHAR(10))
AS
BEGIN
DELETE dbo.CHITIETPHIEUYC
WHERE MAMON=@MAMON
DELETE dbo.MONAN WHERE MAMON=@MAMON
END;

-- Thêm món ăn
GO
ALTER PROC [dbo].[ThemMA](@MAMON VARCHAR(10), @MANHOMMON NCHAR(10),@TENMON NVARCHAR(100), @DONVITINH NCHAR(10), @GIA INT)
AS
BEGIN
INSERT dbo.MONAN
        ( MAMON ,
          MANHOMMON ,
          TENMON ,
          DONVITINH ,
          GIA
        )
VALUES  (@MAMON,@MANHOMMON,@TENMON,@DONVITINH,@GIA)
END;
-- Sửa món ăn
GO
ALTER PROC [dbo].[SuaMA](@MAMON VARCHAR(10), @MANHOMMON NCHAR(10),@TENMON NVARCHAR(100), @DONVITINH NCHAR(10), @GIA INT)
AS
BEGIN
UPDATE dbo.MONAN
SET MANHOMMON=@MANHOMMON,TENMON=@TENMON,DONVITINH=@DONVITINH,GIA=@GIA
WHERE MAMON=@MAMON
END;
-- Đưa ra daanh sách món ăn
GO
ALTER PROC [dbo].[MA_SelectAll]
AS
BEGIN
SELECT MAMON,TENNHOMMON,TENMON,DONVITINH,GIA FROM dbo.MONAN INNER JOIN dbo.NHOMMONAN ON NHOMMONAN.MANHOMMON = MONAN.MANHOMMON
END;

go
EXEC dbo.MA_SelectAll

-- Tìm kiếm
SELECT MAMON,TENNHOMMON,TENMON,DONVITINH,GIA FROM dbo.MONAN INNER JOIN dbo.NHOMMONAN ON NHOMMONAN.MANHOMMON = MONAN.MANHOMMON

--

--Thủ tục đưa ra danh sách phiếu yêu cầu
GO
ALTER PROC [dbo].[PYC_SelectAll]
AS
BEGIN
	SELECT MAPHIEU,KHACHHANG.MAKH,TENKH,MANV,NGAYNHAP,TRANGTHAI FROM dbo.PHIEUYC INNER JOIN dbo.KHACHHANG ON KHACHHANG.MAKH = PHIEUYC.MAKH WHERE TRANGTHAI=N'Chưa thanh toán'
END
-- Thêm Phiếu YC
GO
ALTER PROC ThemPYC(@MAPHIEU VARCHAR(10), @MAKH VARCHAR(10), @MANV VARCHAR(10), @NGAYNHAP DATE, @TRANGTHAI NVARCHAR(50))
AS
BEGIN
	INSERT INTO dbo.PHIEUYC
	        ( MAPHIEU ,
	          MAKH ,
	          MANV ,
	          NGAYNHAP,
			  TRANGTHAI
	        )
	VALUES  ( @MAPHIEU,@MAKH,@MANV,@NGAYNHAP,N'Chưa thanh toán')
END
GO
EXEC dbo.ThemPYC @MAPHIEU = '', -- varchar(10)
    @MAKH = '', -- varchar(10)
    @MANV = '', -- varchar(10)
    @NGAYNHAP = '2018-04-22 17:09:27', -- date
    @TRANGTHAI = N'' -- nvarchar(50)

-- Sửa Phiếu YC
GO
ALTER PROC SuaPYC(@MAPHIEU VARCHAR(10), @MAKH VARCHAR(10), @MANV VARCHAR(10), @NGAYNHAP DATE,@TRANGTHAI NVARCHAR(50))
AS
BEGIN
	UPDATE dbo.PHIEUYC
	SET MAKH =@MAKH,MANV=@MANV,NGAYNHAP=@NGAYNHAP,TRANGTHAI=N'Chưa thanh toán'
	WHERE MAPHIEU=@MAPHIEU
END

-- Xóa Phiếu YC
GO
ALTER PROC XoaPYC(@MAPHIEU VARCHAR(10))
AS
BEGIN
	DELETE dbo.CHITIETPHIEUYC
	WHERE MAPHIEU=@MAPHIEU
	DELETE dbo.PHIEUYC
	WHERE MAPHIEU=@MAPHIEU
END



-- Thủ tục xem thông tin chi tiết phiếu yêu cầu
GO
ALTER PROC [dbo].[CTPYC_SelectAll]
AS
BEGIN
	SELECT CHITIETPHIEUYC.MAPHIEU,MAMON,SOLUONG,THANHTIEN FROM dbo.CHITIETPHIEUYC INNER JOIN dbo.PHIEUYC ON PHIEUYC.MAPHIEU = CHITIETPHIEUYC.MAPHIEU
END

GO
EXEC CTPYC_SelectAll
-- Thêm CTPYC
GO
ALTER PROC [dbo].[ThemCTPYC](@MAPHIEU VARCHAR(10), @MAMON VARCHAR(10), @SOLUONG INT,@GIA INT,@THANHTIEN INT)
AS
BEGIN
	INSERT INTO dbo.CHITIETPHIEUYC
	        ( MAPHIEU, MAMON, SOLUONG,GIA,THANHTIEN)
	VALUES  (@MAPHIEU,@MAMON,@SOLUONG,@GIA,@SOLUONG*@GIA)
END
-- Sửa CTPYC
GO
ALTER PROC [dbo].[SuaCTPYC](@MAPHIEU VARCHAR(10), @MAMON VARCHAR(10), @SOLUONG INT,@GIA INT,@THANHTIEN INT)
AS
BEGIN
	UPDATE dbo.CHITIETPHIEUYC
	SET SOLUONG=@SOLUONG,GIA=@GIA, THANHTIEN=@GIA*SOLUONG
	WHERE MAPHIEU=@MAPHIEU AND MAMON=@MAMON
END
-- Xóa CTPYC
GO
CREATE PROC XoaCTPYC(@MAPHIEU VARCHAR(10), @MAMON VARCHAR(10))
AS
BEGIN
	DELETE dbo.CHITIETPHIEUYC
	WHERE MAPHIEU=@MAPHIEU AND MAMON=@MAMON
END



GO
SELECT A.MAPHIEU,TENKH,SUM(A.THANHTIEN) AS THANHTOAN
FROM dbo.KHACHHANG, (SELECT CHITIETPHIEUYC.MAPHIEU,MAKH,CHITIETPHIEUYC.MAMON,SOLUONG, THANHTIEN=(SOLUONG*GIA) 
					FROM dbo.CHITIETPHIEUYC INNER JOIN dbo.PHIEUYC
					ON PHIEUYC.MAPHIEU = CHITIETPHIEUYC.MAPHIEU INNER JOIN dbo.MONAN 
					ON MONAN.MAMON = CHITIETPHIEUYC.MAMON AND CHITIETPHIEUYC.MAPHIEU='MP02') A
WHERE A.MAKH=KHACHHANG.MAKH
GROUP BY A.MAPHIEU,TENKH


-- Sau khi thanh toán, sửa trạng thái từ chưa thanh toán sang đã thanh toán
GO
ALTER PROC DaTT(@MAPHIEU VARCHAR(10),@TRANGTHAI NVARCHAR(50))
AS
BEGIN
	UPDATE dbo.PHIEUYC
	SET TRANGTHAI=N'Đã thanh toán'
	WHERE MAPHIEU=@MAPHIEU
END

-- Xem các hóa đơn đã thanh toán SELECT A.MAPHIEU,A.TENKH,A.MANV,A.NGAYNHAP,SUM(A.THANHTIEN) AS TONGTIEN
GO
ALTER PROC [dbo].[HoaDonDaTT]
AS
BEGIN
	SELECT CHITIETPHIEUYC.MAPHIEU,TENKH,MANV,NGAYNHAP,SUM(THANHTIEN) AS TONGTIEN FROM dbo.KHACHHANG INNER JOIN dbo.PHIEUYC ON PHIEUYC.MAKH = KHACHHANG.MAKH INNER JOIN dbo.CHITIETPHIEUYC ON CHITIETPHIEUYC.MAPHIEU = PHIEUYC.MAPHIEU
	WHERE CHITIETPHIEUYC.MAPHIEU='Đã thanh toán'
	GROUP BY CHITIETPHIEUYC.MAPHIEU,TENKH,MANV,NGAYNHAP
END

GO

SELECT MAPHIEU,TENMON,SOLUONG,CHITIETPHIEUYC.GIA,THANHTIEN FROM dbo.CHITIETPHIEUYC INNER JOIN dbo.MONAN ON MONAN.MAMON = CHITIETPHIEUYC.MAMON
WHERE MAPHIEU='MP01'


SELECT * from PHIEUYEUCAU WHERE MAPHIEU like '%MP%'

Select * FROM dbo.NHANVIEN where MABP Like 'BP03'


SELECT A.MAPHIEU,A.TENKH,A.MANV,A.NGAYNHAP,SUM(A.THANHTIEN) AS TONGTIEN FROM dbo.KHACHHANG KH, (SELECT CHITIETPHIEUYC.MAPHIEU, TENKH, MANV, NGAYNHAP, THANHTIEN = (SOLUONG * GIA) FROM dbo.PHIEUYC INNER JOIN dbo.CHITIETPHIEUYC ON CHITIETPHIEUYC.MAPHIEU = PHIEUYC.MAPHIEU  INNER JOIN dbo.MONAN ON MONAN.MAMON = CHITIETPHIEUYC.MAMON INNER JOIN dbo.KHACHHANG ON KHACHHANG.MAKH = PHIEUYC.MAKH WHERE TRANGTHAI = N'Đã thanh toán') A WHERE A.MAPHIEU LIKE'MP08' GROUP BY A.MAPHIEU,A.TENKH,A.MANV,A.NGAYNHAP 


--------- In hóa đơn
--GO
--CREATE PROC TongTien (@MAPHIEU VARCHAR(10))
--AS
--BEGIN
--	 SELECT A.MAPHIEU, SUM(A.THANHTIEN) AS TONGTIEN 
--	 FROM dbo.CHITIETPHIEUYC CT, (SELECT MAPHIEU, THANHTIEN=(SOLUONG*GIA)
--							FROM dbo.CHITIETPHIEUYC INNER JOIN dbo.MONAN
--							ON MONAN.MAMON = CHITIETPHIEUYC.MAMON) A
--	WHERE CT.MAPHIEU=A.MAPHIEU AND CT.MAPHIEU=@MAPHIEU
--	GROUP BY A.MAPHIEU
--END

--GO
--ALTER PROC InHoaDon @MAPHIEU VARCHAR(10)
--AS
--BEGIN
--	SELECT A.MAPHIEU,A.MANV,A.NGAYNHAP,A.MAKH,A.TENKH,A.TENMON,A.SOLUONG,A.DONVITINH,A.GIA, A.THANHTIEN, SUM(A.THANHTIEN) AS TONGTIEN
--	FROM dbo.KHACHHANG KH, ( SELECT CHITIETPHIEUYC.MAPHIEU,MANV,NGAYNHAP,KHACHHANG.MAKH,TENKH,TENMON,SOLUONG,DONVITINH,GIA, THANHTIEN=(SOLUONG*GIA) FROM dbo.KHACHHANG INNER JOIN dbo.PHIEUYC
--	 ON PHIEUYC.MAKH = KHACHHANG.MAKH INNER JOIN dbo.CHITIETPHIEUYC 
--	 ON CHITIETPHIEUYC.MAPHIEU = PHIEUYC.MAPHIEU INNER JOIN dbo.MONAN 
--	 ON MONAN.MAMON = CHITIETPHIEUYC.MAMON) A
--	 WHERE A.MAKH=KH.MAKH 
--	 GROUP BY A.MAPHIEU,A.MANV,A.NGAYNHAP,A.MAKH,A.TENKH,A.TENMON,A.SOLUONG, A.DONVITINH,A.GIA,A.THANHTIEN
--END
-----------------------
-- Thông tin tiêu đề hóa đơn

	

	SELECT TENMON,SOLUONG,DONVITINH,GIA,THANHTIEN=(SOLUONG*GIA) FROM dbo.CHITIETPHIEUYC INNER JOIN dbo.MONAN ON MONAN.MAMON = CHITIETPHIEUYC.MAMON WHERE MAPHIEU=''


SELECT SUM(A.THANHTIEN) AS TONGTIEN
FROM dbo.KHACHHANG KH,(SELECT CHITIETPHIEUYC.MAPHIEU,MANV,NGAYNHAP,KHACHHANG.MAKH,TENKH,THANHTIEN=(SOLUONG*GIA) FROM dbo.KHACHHANG INNER JOIN dbo.PHIEUYC ON PHIEUYC.MAKH = KHACHHANG.MAKH INNER JOIN dbo.CHITIETPHIEUYC ON CHITIETPHIEUYC.MAPHIEU = PHIEUYC.MAPHIEU INNER JOIN dbo.MONAN ON MONAN.MAMON = CHITIETPHIEUYC.MAMON)A
WHERE A.MAKH=KH.MAKH AND A.MAPHIEU='MP05'


SELECT CHITIETPHIEUYC.MAPHIEU,MANV,NGAYNHAP,KHACHHANG.MAKH,TENKH,THANHTIEN=(SOLUONG*GIA) FROM dbo.KHACHHANG INNER JOIN dbo.PHIEUYC ON PHIEUYC.MAKH = KHACHHANG.MAKH INNER JOIN dbo.CHITIETPHIEUYC ON CHITIETPHIEUYC.MAPHIEU = PHIEUYC.MAPHIEU INNER JOIN dbo.MONAN ON MONAN.MAMON = CHITIETPHIEUYC.MAMON WHERE CHITIETPHIEUYC.MAPHIEU='MP05'


SELECT CHITIETPHIEUYC.MAPHIEU,MANV,NGAYNHAP,KHACHHANG.MAKH,TENKH,SUM(THANHTIEN) AS TONGTIEN 
FROM dbo.KHACHHANG INNER JOIN dbo.PHIEUYC 
ON PHIEUYC.MAKH = KHACHHANG.MAKH INNER JOIN dbo.CHITIETPHIEUYC
 ON CHITIETPHIEUYC.MAPHIEU = PHIEUYC.MAPHIEU INNER JOIN dbo.MONAN
  ON MONAN.MAMON = CHITIETPHIEUYC.MAMON 
  WHERE CHITIETPHIEUYC.MAPHIEU='MP01' 
GROUP BY CHITIETPHIEUYC.MAPHIEU, MANV, NGAYNHAP, KHACHHANG.MAKH, TENKH