-- Đưa ra danh sách nhóm món ăn
GO
CREATE PROC NM_SelectAll
AS
BEGIN
	SELECT * FROM dbo.NHOMMONAN
END
-- Đưa ra daanh sách món ăn
GO
ALTER PROC [dbo].[MA_SelectAll]
AS
BEGIN
SELECT MAMON,TENNHOMMON,TENMON,DONVITINH,GIA FROM dbo.MONAN INNER JOIN dbo.NHOMMONAN ON NHOMMONAN.MANHOMMON = MONAN.MANHOMMON
END;

go
EXEC dbo.MA_SelectAll

-- Tìm kiếm
SELECT MAMON,TENNHOMMON,TENMON,DONVITINH,GIA FROM dbo.MONAN INNER JOIN dbo.NHOMMONAN ON NHOMMONAN.MANHOMMON = MONAN.MANHOMMON

--

--Thủ tục đưa ra danh sách phiếu yêu cầu
GO
CREATE PROC PYC_SelectAll
AS
BEGIN
	SELECT * FROM dbo.PHIEUYC
END
-- Thêm Phiếu YC
GO
CREATE PROC ThemPYC(@MAPHIEU VARCHAR(10), @MAKH VARCHAR(10), @MANV VARCHAR(10), @NGAYNHAP DATE)
AS
BEGIN
	INSERT INTO dbo.PHIEUYC
	        ( MAPHIEU ,
	          MAKH ,
	          MANV ,
	          NGAYNHAP 
	        )
	VALUES  ( @MAPHIEU,@MAKH,@MANV,@NGAYNHAP)
END
-- Sửa Phiếu YC
GO
CREATE PROC SuaPYC(@MAPHIEU VARCHAR(10), @MAKH VARCHAR(10), @MANV VARCHAR(10), @NGAYNHAP DATE)
AS
BEGIN
	UPDATE dbo.PHIEUYC
	SET MAKH =@MAKH,MANV=@MANV,NGAYNHAP=@NGAYNHAP
	WHERE MAPHIEU=@MAPHIEU
END

-- Xóa Phiếu YC
GO
CREATE PROC XoaPYC(@MAPHIEU VARCHAR(10))
AS
BEGIN
	UPDATE dbo.CHITIETPHIEUYC
	SET MAPHIEU=NULL
	WHERE MAPHIEU=@MAPHIEU
	DELETE dbo.PHIEUYC
	WHERE MAPHIEU=@MAPHIEU
END

EXEC dbo.ThemPYC @MAPHIEU = 'MP04', -- varchar(10)
    @MAKH = 'KH03', -- varchar(10)
    @MANV = 'NV02', -- varchar(10)
    @NGAYNHAP = '2018-04-11' -- date

-- Thủ tục xem thông tin chi tiết phiếu yêu cầu
GO
ALTER PROC CTPYC_SelectAll
AS
BEGIN
	SELECT CHITIETPHIEUYC.MAPHIEU,MAMON,SOLUONG FROM dbo.CHITIETPHIEUYC INNER JOIN dbo.PHIEUYC ON PHIEUYC.MAPHIEU = CHITIETPHIEUYC.MAPHIEU AND CHITIETPHIEUYC.MAPHIEU='MP02'
END

GO
EXEC CTPYC_SelectAll
-- Thêm CTPYC
GO
CREATE PROC ThemCTPYC(@MAPHIEU VARCHAR(10), @MAMON VARCHAR(10), @SOLUONG INT)
AS
BEGIN
	INSERT INTO dbo.CHITIETPHIEUYC
	        ( MAPHIEU, MAMON, SOLUONG )
	VALUES  (@MAPHIEU,@MAMON,@SOLUONG)
END
-- Sửa CTPYC
GO
ALTER PROC SuaCTPYC(@MAPHIEU VARCHAR(10), @MAMON VARCHAR(10), @SOLUONG INT)
AS
BEGIN
	UPDATE dbo.CHITIETPHIEUYC
	SET SOLUONG=@SOLUONG
	WHERE MAPHIEU=@MAPHIEU AND MAMON=@MAMON
END
-- Xóa CTPYC
GO
CREATE PROC XoaCTPYC(@MAPHIEU VARCHAR(10), @MAMON VARCHAR(10))
AS
BEGIN
	DELETE dbo.CHITIETPHIEUYC
	WHERE MAPHIEU=@MAPHIEU AND MAMON=@MAMON
END

EXEC dbo.ThemCTPYC @MAPHIEU = 'MP03', -- varchar(10)
    @MAMON = 'MA04', -- varchar(10)
    @SOLUONG = 2 -- int

EXEC dbo.SuaCTPYC @MAPHIEU = 'MP03', -- varchar(10)
    @MAMON = 'MA04', -- varchar(10)
    @SOLUONG = 1 -- int

GO
SELECT CHITIETPHIEUYC.MAPHIEU,CHITIETPHIEUYC.MAMON,SOLUONG, THANHTIEN=(SOLUONG*GIA) FROM dbo.CHITIETPHIEUYC INNER JOIN dbo.PHIEUYC ON PHIEUYC.MAPHIEU = CHITIETPHIEUYC.MAPHIEU INNER JOIN dbo.MONAN ON MONAN.MAMON = CHITIETPHIEUYC.MAMON AND CHITIETPHIEUYC.MAPHIEU='MP02'

SELECT * FROM dbo.MONAN

------

GO
SELECT A.MAPHIEU,TENKH,SUM(A.THANHTIEN) AS THANHTOAN
FROM dbo.KHACHHANG, (SELECT CHITIETPHIEUYC.MAPHIEU,MAKH,CHITIETPHIEUYC.MAMON,SOLUONG, THANHTIEN=(SOLUONG*GIA) 
					FROM dbo.CHITIETPHIEUYC INNER JOIN dbo.PHIEUYC
					ON PHIEUYC.MAPHIEU = CHITIETPHIEUYC.MAPHIEU INNER JOIN dbo.MONAN 
					ON MONAN.MAMON = CHITIETPHIEUYC.MAMON AND CHITIETPHIEUYC.MAPHIEU='MP02') A
WHERE A.MAKH=KHACHHANG.MAKH
GROUP BY A.MAPHIEU,TENKH

GO
CREATE PROC Pr_ThanhToan(@MAPHIEU VARCHAR(10))
AS
BEGIN
	SELECT A.MAPHIEU,TENKH,SUM(A.THANHTIEN) AS THANHTOAN
	FROM dbo.KHACHHANG, (SELECT CHITIETPHIEUYC.MAPHIEU,MAKH,CHITIETPHIEUYC.MAMON,SOLUONG, THANHTIEN=(SOLUONG*GIA) 
					FROM dbo.CHITIETPHIEUYC INNER JOIN dbo.PHIEUYC
					ON PHIEUYC.MAPHIEU = CHITIETPHIEUYC.MAPHIEU INNER JOIN dbo.MONAN 
					ON MONAN.MAMON = CHITIETPHIEUYC.MAMON AND CHITIETPHIEUYC.MAPHIEU=@MAPHIEU) A
	WHERE A.MAKH=KHACHHANG.MAKH
	GROUP BY A.MAPHIEU,TENKH
END

GO
EXEC dbo.Pr_ThanhToan @MAPHIEU = 'MP03' -- varchar(10)


